spring:
  datasource:
      url: jdbc:mysql://8.136.95.29:3306/mydemo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 1996Yu0802
mybatis:
   mapperLocations: classpath:/mapper/*.xml
