spring:
  datasource:
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: '0000'
mybatis:
   mapperLocations: classpath:/mapper/*.xml
